### Testing of Python behaviour during the solving of Advent of Code 2023

In [3]:
import re
a = "...123.45..."
list = re.findall('\d+', a)
list

['123', '45']

In [4]:
b = [1] * 10
b

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [1]:
for i in range(10):
    i = 11
    print(i)

11
11
11
11
11
11
11
11
11
11


Cycling trough a list

In [ ]:
directions = [5] * 10

if i >= len(directions):
    i = 0
...
i += 1

# rewriten as:
i = (i + 1) % len(directions)


Least Common Multple (LCM), * operator for unpacking

In [4]:
import math
x = math.lcm(2,3,4)
print(x)
nums = [6,8,12]
math.lcm(*nums)

12


24

In [3]:
ascii('\n')

"'\\n'"

In [6]:
boxes = [[] for _ in range(5)]
boxes

[[], [], [], [], []]

In [11]:
import numpy as np

M = np.ones((5,5), dtype="int8")
M[1:4,1:4] = 0
M[2,2] = 9
M

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [12]:
import numpy as np

# Example NumPy array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# List of row indices to double
row_indices = [0, 2]  # Example indices

# Doubling the specified rows
for idx in row_indices:
    array[idx] *= 2

# The array after doubling the specified rows
print(array)


[[ 2  4  6]
 [ 4  5  6]
 [14 16 18]]
